### ISSUE TITLE
Example did not run properly

### ISSUE THREAD

**Issue by elong0527** [Merck/metalite#149]
https://merck.github.io/metalite/reference/meta_run.html

**Comment by nanxstats** [comment]
I'm not a non-standard evaluation expert, but I suspect that this is because the `eval()` in `meta_run()` is searching in the wrong scope hence cannot find the function defined in the global environment.

Here is a minimal reproducible example to help you experiment with potential solutions. The example code runs ok in regular interactive sessions but under pkgdown it would throw "could not find function 'f'":

```r
#' Title
#'
#' @export
#'
#' @examples
#' f <- function (x) x + 1
#' meta_run()
meta_run <- function() eval(parse(text = "f(1)"))
```

**Comment by wangben718** [comment]
Thanks @nanxstats . Should we resolve this issue after we release our new version?

**Comment by elong0527** [comment]
Sounds good!

**Comment by nanxstats** [comment]
> Thanks @nanxstats . Should we resolve this issue after we release our new version?

Agreed, this shouldn't be a blocker for releases. We should prioritize the release.

**Comment by nanxstats** [comment]
@elong0527 will create a minimal reproducible example package to investigate why this runs ok in vignettes but not function reference pages, possibly an item for upstream feedback.
